import matplotlib.pyplot as plt
import numpy as np
x1, y1= np.genfromtxt('data/lange_Spule.txt',delimiter=',', unpack=True)
x2 , y2 = np.genfromtxt('data/kurze_Spule.txt',delimiter=',', unpack=True)
x3 , y3 = np.genfromtxt('data/dicke_Spule.txt',delimiter=',', unpack=True)
x4 , y4 =np.genfromtxt('data/Hysteresekurve.txt',delimiter=',', unpack=True)
x5 , y5 =np.genfromtxt('data/H_abstand6.txt', delimiter=',',unpack=True)
x6 , y6 =np.genfromtxt('data/H_abstand12.txt', delimiter=',',unpack=True)
x7 , y7 =np.genfromtxt('data/H_abstand18.txt', delimiter=',',unpack=True)

plt.plot(x1, y1,'bx', label='lange Spule')
plt.xlabel(r'$x \:/\: \si{\cm}$')
plt.ylabel(r'$B \:/\: \si{\milli\tesla}$')
plt.legend(loc='best')
plt.grid()
plt.savefig('build/lange_Spule.pdf')
plt.clf()

plt.plot(x2, y2,'bx', label='kurze Spule')
plt.xlabel(r'$x \:/\: \si{\cm}$')
plt.ylabel(r'$B \:/\: \si{\milli\tesla}$')
plt.legend(loc='best')
plt.grid()
plt.savefig('build/kurze_Spule.pdf')
plt.clf()

plt.plot(x3, y3,'bx', label='dicke Spule')
plt.xlabel(r'$x \:/\: \si{\cm}$')
plt.ylabel(r'$B \:/\: \si{\milli\tesla}$')
plt.legend(loc='best')
plt.grid()
plt.savefig('build/dicke_Spule.pdf')
plt.clf()

plt.plot(x4, y4,'b.', label='Hysteresekurve')
plt.xlabel(r'$x \:/\: \si{\cm}$')
plt.ylabel(r'$B \:/\: \si{\milli\tesla}$')
plt.legend(loc='best')
plt.grid()
plt.savefig('build/Hysteresekurve.pdf')
plt.clf()

plt.plot(x5, y5,'b.', label='Spulenabstand: 6,25 \si{\centi\m}')
plt.xlabel(r'$x \:/\: \si{\cm}$')
plt.ylabel(r'$B \:/\: \si{\milli\tesla}$')
plt.legend(loc='best')
plt.grid()
plt.savefig('build/H_abstand6.pdf')
plt.clf()

plt.plot(x6, y6,'b.', label='Spulenabstand: 12,50 \si{\centi\m}')
plt.xlabel(r'$x \:/\: \si{\cm}$')
plt.ylabel(r'$B \:/\: \si{\milli\tesla}$')
plt.legend(loc='best')
plt.grid()
plt.savefig('build/H_abstand12.pdf')
plt.clf()

plt.plot(x7, y7,'b.', label='Spulenabstand: 18,75 \si{\centi\m}')
plt.xlabel(r'$x \:/\: \si{\cm}$')
plt.ylabel(r'$B \:/\: \si{\milli\tesla}$')
plt.legend(loc='best')
plt.grid()
plt.savefig('build/H_abstand18.pdf')
plt.clf()